### ISSUE TITLE
mediaplayer-app creates duplicate of the original video

### ISSUE THREAD

**Issue by lazmol** [ubports/mediaplayer-app#4]
**What happened:**
When a video is opened from the File Manager app I have to wait some time (can take minutes depending on the video size) till the file manager creates a duplicate (e.g. video(1).mp4) and plays the video.
**What I expected to happen:**
Video should start playing instantly in mediaplayer-app. When opening the video from the Gallery app or from the Video scopes the video starts playing without making a duplicate. So maybe the bug is something to do with the File Manager app.

**Software Version:**
phablet@ubuntu-phablet:~$ system-image-cli --info
current build number: 2
device name: frieza
channel: ubports-touch/15.04/rc
last update: 2017-06-11 12:54:56
version version: 2
version ubports: 20170610-30270
version keyring: archive-master
version device: 20170524-20895

**Comment by Flohack74** [comment]
Perhaps it falls also in this category: https://github.com/ubports/filemanager-app/issues/2 - The design of the file/data interchanges is really a bit cumbersome.

**Comment by paulmueller** [comment]
I observe this issue when I open a video in the file manager.

**Comment by lazmol** [comment]
Yes it only happens thru File Manager. The video is not on the SD card just in ~/Videos.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/mediaplayer-app/-/issues/4

Sorry for your inconvenience.
