### ISSUE TITLE
Video playback has distorted colors

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/mediaplayer-app#9]
This is OTA-3 on a Nexus 5 (hammerhead).
Videos I have recorded with the camera app have distorted colors when played back. It looks as if the color planes were shifted against each other.
The video looks fine when I play it on my desktop.
Here are screenshots of how the video looks in playback, and how it should look like (taken from preview, which looks okay):
![screenshot20180524_100538442](https://user-images.githubusercontent.com/21172886/40477071-d92b6dcc-5f45-11e8-9fcf-33d5e17bd578.png)
![screenshot20180524_100624273](https://user-images.githubusercontent.com/21172886/40477336-819824be-5f46-11e8-8a36-79839a27c053.png)

**Comment by Flohack74** [comment]
This has nothing to do with the app itself and is tracked here: https://github.com/ubports/ubuntu-touch/issues/7

**Comment by ruedigerkupper** [comment]
Thank you. I wonder how a resonably educated average user should know where to report which bug for UT. I do consider myself an experienced user and still I frequently fail, as was just seen. UT makes it currently very hard to report bugs (and at the right place).
Can this be improved?
